extension_dir="C:\Users\IT Maurice\AppData\Local\Microsoft\WinGet\Packages\PHP.PHP.8.4_Microsoft.Winget.Source_8wekyb3d8bbwe\ext"
extension=mbstring
extension=openssl
extension=pdo_sqlite
extension=pdo_mysql
extension=sqlite3
extension=fileinfo
upload_max_filesize=250M
post_max_size=260M
max_execution_time=300
max_input_time=300
memory_limit=512M
upload_tmp_dir="C:\Users\IT Maurice\Downloads\dvx\storage\app\private\upload-tmp"
sys_temp_dir="C:\Users\IT Maurice\Downloads\dvx\storage\app\private\upload-tmp"
