import { Head, Link, router } from '@inertiajs/react';
import { Button } from '@mui/material';

export default function EmployeeHistory({ employee, summary, history }: { employee: any; summary: Record<string, number>; history: any }) {
    const current = employee.team_membership?.team;

    return <main className="assessment-admin min-h-full bg-[#f7f7fa] p-6"><Head title={`${employee.name} QA History`} /><div className="mx-auto max-w-6xl space-y-5"><header><Link className="font-semibold text-red-700" href="/management/qa-dashboard">← QA Dashboard</Link><h1 className="mt-2">{employee.name}</h1><p>{current?.campaign?.name || 'Historical campaign view'} · {current?.name || 'Historical team view'}</p></header><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[['Average QA Score', `${summary.average_score}%`],['Total Evaluations', summary.total],['Passed', summary.passed],['Failed', summary.failed],['Open Coaching', summary.open_coaching]].map(([label,value]) => <div className="rounded-xl border bg-white p-4" key={String(label)}><p className="text-xs font-bold text-slate-500 uppercase">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></div>)}</section><section><h2 className="mb-3 text-xl font-bold">Evaluation History</h2><div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[850px] text-left text-sm"><thead><tr>{['Date','Scorecard','Evaluator','Score','Result','Coaching','Action'].map((h) => <th className="px-4 py-3" key={h}>{h}</th>)}</tr></thead><tbody>{history.data.map((row: any) => <tr className="border-t" key={row.id}><td className="px-4 py-3">{new Date(row.call_at).toLocaleDateString()}</td><td className="px-4 py-3">{row.scorecard_name}</td><td className="px-4 py-3">{row.evaluator.name}</td><td className="px-4 py-3">{row.percentage}%</td><td className="px-4 py-3 font-semibold">{row.has_critical_failure ? 'Failed — Critical' : row.result}</td><td className="px-4 py-3">{row.coaching_record?.status ? row.coaching_record.status.replaceAll('_',' ') : 'Not Created'}</td><td className="px-4 py-3"><Link className="font-semibold text-red-700" href={`/management/call-evaluations/${row.id}`}>View</Link></td></tr>)}</tbody></table></div><div className="mt-3 flex justify-end gap-2">{history.prev_page_url && <Button onClick={() => router.get(history.prev_page_url)}>Previous</Button>}{history.next_page_url && <Button onClick={() => router.get(history.next_page_url)}>Next</Button>}</div></section></div></main>;
}
EmployeeHistory.layout = { breadcrumbs: [{ title: 'Quality Assurance', href: '/management/qa-dashboard' }, { title: 'Employee QA History', href: '#' }] };
