<?php

use App\Http\Controllers\ApplicantStatusController;
use App\Http\Controllers\AssessmentAssignmentController;
use App\Http\Controllers\AssessmentBuilderController;
use App\Http\Controllers\AssessmentManagementController;
use App\Http\Controllers\AssessmentMaterialController;
use App\Http\Controllers\AssessmentNotificationController;
use App\Http\Controllers\AssessmentQuestionBankController;
use App\Http\Controllers\AssessmentQuestionController;
use App\Http\Controllers\AssessmentRandomPoolController;
use App\Http\Controllers\AssessmentReportingController;
use App\Http\Controllers\AssessmentTrainingAttachmentController;
use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\CallEvaluationController;
use App\Http\Controllers\CallEvaluationScorecardChildController;
use App\Http\Controllers\CallEvaluationScorecardController;
use App\Http\Controllers\CampaignAnalyticsController;
use App\Http\Controllers\CampaignController;
use App\Http\Controllers\CoachingManagementController;
use App\Http\Controllers\EmployeeAssessmentController;
use App\Http\Controllers\EmployeeAssessmentReportController;
use App\Http\Controllers\EmployeeCoachingController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\EmployeeTrainingProfileController;
use App\Http\Controllers\JobApplicationController;
use App\Http\Controllers\QaDashboardController;
use App\Http\Controllers\RequestApprovalController;
use App\Http\Controllers\SimpleAssessmentController;
use App\Http\Controllers\TeamAssignmentController;
use App\Http\Controllers\TeamController;
use App\Http\Controllers\TrainingLibraryController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function (Request $request) {
    Auth::guard('web')->logout();
    $request->session()->invalidate();
    $request->session()->regenerateToken();

    return to_route('login');
})->name('home');
Route::inertia('/careers', 'welcome')->name('careers');
Route::post('apply', [JobApplicationController::class, 'store'])->middleware('throttle:5,1')->name('applications.store');
Route::get('application-status/challenge', [ApplicantStatusController::class, 'challenge'])->middleware('throttle:10,1')->name('application-status.challenge');
Route::post('application-status', [ApplicantStatusController::class, 'lookup'])->middleware('throttle:5,10')->name('application-status.lookup');

Route::middleware(['auth', 'verified'])->group(function () {
    Route::inertia('dashboard', 'dashboard')->name('dashboard');
    Route::get('attendance', [AttendanceController::class, 'index'])->name('attendance');
    Route::put('attendance/{employee}/time', [AttendanceController::class, 'overrideTime'])->name('attendance.override-time');
    Route::middleware('qa.viewer')->group(function () {
        Route::get('management/qa-dashboard', [QaDashboardController::class, 'index'])->name('quality.dashboard');
        Route::get('management/qa-dashboard/export', [QaDashboardController::class, 'export'])->name('quality.dashboard.export');
        Route::get('management/qa-dashboard/employees/{employee}', [QaDashboardController::class, 'employee'])->name('quality.dashboard.employee');
        Route::get('management/call-evaluations', [CallEvaluationController::class, 'index'])->name('quality.evaluations.index');
        Route::get('management/call-evaluations/{evaluation}/recording', [CallEvaluationController::class, 'recording'])->whereNumber('evaluation')->name('quality.evaluations.recording');
        Route::get('management/call-evaluations/{evaluation}/document', [CallEvaluationController::class, 'document'])->whereNumber('evaluation')->name('quality.evaluations.document');
        Route::get('management/call-evaluations/{evaluation}', [CallEvaluationController::class, 'show'])->whereNumber('evaluation')->name('quality.evaluations.show');
        Route::get('management/coaching', [CoachingManagementController::class, 'index'])->name('coaching.manage.index');
        Route::get('management/coaching/{coaching}/export', \App\Http\Controllers\CoachingExportController::class)->name('coaching.manage.export');
        Route::get('management/coaching/{coaching}', [CoachingManagementController::class, 'show'])->name('coaching.manage.show');
        Route::get('management/employees/{employee}/training-profile', [EmployeeTrainingProfileController::class, 'show'])->name('coaching.profile');
    });
    Route::get('requests', [RequestApprovalController::class, 'index'])->name('requests');
    Route::patch('requests/{type}/{requestId}/status', [RequestApprovalController::class, 'updateStatus'])->name('requests.update-status');
    Route::get('campaigns', [CampaignController::class, 'index'])->name('campaigns');
    Route::post('campaigns', [CampaignController::class, 'store'])->name('campaigns.store');
    Route::put('campaigns/{campaign}', [CampaignController::class, 'update'])->name('campaigns.update');
    Route::delete('campaigns/{campaign}', [CampaignController::class, 'destroy'])->name('campaigns.destroy');
    Route::get('teams', [TeamController::class, 'index'])->name('teams');
    Route::post('teams', [TeamController::class, 'store'])->name('teams.store');
    Route::put('teams/{team}', [TeamController::class, 'update'])->name('teams.update');
    Route::delete('teams/{team}', [TeamController::class, 'destroy'])->name('teams.destroy');
    Route::get('team-assigning', [TeamAssignmentController::class, 'index'])->name('team-assigning');
    Route::post('team-assigning', [TeamAssignmentController::class, 'store'])->name('team-assigning.store');
    Route::post('team-assigning/transfer', [TeamAssignmentController::class, 'transfer'])->name('team-assigning.transfer');
    Route::get('employees', [EmployeeController::class, 'index'])->name('employees');
    Route::post('employees', [EmployeeController::class, 'store'])->name('employees.store');
    Route::put('employees/{employee}', [EmployeeController::class, 'update'])->name('employees.update');
    Route::get('assessments', [EmployeeAssessmentController::class, 'index'])->name('assessments.index');
    Route::get('assessments/history', [EmployeeAssessmentReportController::class, 'history'])->name('assessments.history');
    Route::get('assessments/progress', [EmployeeAssessmentReportController::class, 'progress'])->name('assessments.progress');
    Route::get('notifications', [AssessmentNotificationController::class, 'index'])->name('notifications.index');
    Route::patch('notifications/{notification}/read', [AssessmentNotificationController::class, 'read'])->name('notifications.read');
    Route::get('my-coaching', [EmployeeCoachingController::class, 'index'])->name('coaching.my.index');
    Route::get('my-coaching/{coaching}', [EmployeeCoachingController::class, 'show'])->name('coaching.my.show');
    Route::post('my-coaching/{coaching}/acknowledge', [EmployeeCoachingController::class, 'acknowledge'])->name('coaching.my.acknowledge');
    Route::post('my-coaching/{coaching}/training/{assignment}/open', [EmployeeCoachingController::class, 'open'])->name('coaching.my.training.open');
    Route::post('my-coaching/{coaching}/training/{assignment}/complete', [EmployeeCoachingController::class, 'complete'])->name('coaching.my.training.complete');
    Route::get('my-coaching/{coaching}/training/{assignment}/media', [EmployeeCoachingController::class, 'media'])->name('coaching.my.training.media');
    Route::prefix('assessments')->name('assessments.my.')->group(function () {
        Route::get('assignments/{assignment}/training', [EmployeeAssessmentController::class, 'training'])->name('training');
        Route::post('assignments/{assignment}/materials/{material}/open', [EmployeeAssessmentController::class, 'openMaterial'])->name('materials.open');
        Route::post('assignments/{assignment}/materials/{material}/complete', [EmployeeAssessmentController::class, 'completeMaterial'])->name('materials.complete');
        Route::post('assignments/{assignment}/library-attachments/{attachment}/open', [EmployeeAssessmentController::class, 'openLibraryMaterial'])->name('library.open');
        Route::post('assignments/{assignment}/library-attachments/{attachment}/complete', [EmployeeAssessmentController::class, 'completeLibraryMaterial'])->name('library.complete');
        Route::get('assignments/{assignment}/library-attachments/{attachment}/media', [EmployeeAssessmentController::class, 'libraryMedia'])->name('library.media');
        Route::get('assignments/{assignment}/materials/{material}/media', [EmployeeAssessmentController::class, 'media'])->name('materials.media');
        Route::post('assignments/{assignment}/start', [EmployeeAssessmentController::class, 'start'])->name('start');
        Route::get('attempts/{attempt}', [EmployeeAssessmentController::class, 'showAttempt'])->name('attempts.show');
        Route::get('attempts/{attempt}/review', [EmployeeAssessmentController::class, 'review'])->name('attempts.review');
        Route::put('attempts/{attempt}/answer', [EmployeeAssessmentController::class, 'autosave'])->name('attempts.autosave');
        Route::put('attempts/{attempt}/flag', [EmployeeAssessmentController::class, 'flag'])->name('attempts.flag');
        Route::post('attempts/{attempt}/submit', [EmployeeAssessmentController::class, 'submit'])->name('attempts.submit');
        Route::get('attempts/{attempt}/result', [EmployeeAssessmentController::class, 'result'])->name('results');
    });

    Route::prefix('management/assessments')->middleware('assessment.manager')->group(function () {
        Route::get('/', [AssessmentManagementController::class, 'index'])->name('assessments.manage');
        Route::get('create', [SimpleAssessmentController::class, 'create'])->name('assessments.simple.create');
        Route::post('simple', [SimpleAssessmentController::class, 'store'])->name('assessments.simple.store');
        Route::get('schedule', [AssessmentManagementController::class, 'schedule'])->name('assessments.schedule');
        Route::post('/', [AssessmentManagementController::class, 'store'])->name('assessments.store');
        Route::put('{assessment}', [AssessmentManagementController::class, 'update'])->name('assessments.update');
        Route::post('{assessment}/clone', [AssessmentManagementController::class, 'clone'])->name('assessments.clone');
        Route::get('{assessment}/preview', [AssessmentManagementController::class, 'preview'])->name('assessments.preview');
        Route::patch('{assessment}/publish', [AssessmentManagementController::class, 'publish'])->name('assessments.publish');
        Route::patch('{assessment}/archive', [AssessmentManagementController::class, 'archive'])->name('assessments.archive');
        Route::get('{assessment}/builder', [AssessmentBuilderController::class, 'edit'])->name('assessments.builder');
        Route::get('{assessment}/simple-builder', [SimpleAssessmentController::class, 'builder'])->name('assessments.simple.builder');
        Route::get('{assessment}/review', [SimpleAssessmentController::class, 'review'])->name('assessments.simple.review');
        Route::get('{assessment}/simple-schedule', [SimpleAssessmentController::class, 'schedule'])->name('assessments.simple.schedule');
        Route::patch('{assessment}/simple-schedule', [SimpleAssessmentController::class, 'saveSchedule'])->name('assessments.simple.schedule.save');
        Route::get('{assessment}/simple-question-bank', [SimpleAssessmentController::class, 'bank'])->name('assessments.simple.bank');
        Route::post('{assessment}/simple-question-bank', [SimpleAssessmentController::class, 'useBanks'])->name('assessments.simple.bank.use-many');
        Route::post('{assessment}/simple-question-bank/{question}', [SimpleAssessmentController::class, 'useBank'])->name('assessments.simple.bank.use');
        Route::post('{assessment}/materials', [AssessmentMaterialController::class, 'store'])->name('assessments.materials.store');
        Route::patch('{assessment}/materials/reorder', [AssessmentMaterialController::class, 'reorder'])->name('assessments.materials.reorder');
        Route::put('{assessment}/materials/{material}', [AssessmentMaterialController::class, 'update'])->name('assessments.materials.update');
        Route::delete('{assessment}/materials/{material}', [AssessmentMaterialController::class, 'destroy'])->name('assessments.materials.destroy');
        Route::post('{assessment}/questions', [AssessmentQuestionController::class, 'store'])->name('assessments.questions.store');
        Route::post('{assessment}/questions/from-bank', [AssessmentQuestionBankController::class, 'addToAssessment'])->name('assessments.questions.from-bank');
        Route::post('{assessment}/random-pools', [AssessmentRandomPoolController::class, 'store'])->name('assessments.random-pools.store');
        Route::put('{assessment}/random-pools/{pool}', [AssessmentRandomPoolController::class, 'update'])->name('assessments.random-pools.update');
        Route::delete('{assessment}/random-pools/{pool}', [AssessmentRandomPoolController::class, 'destroy'])->name('assessments.random-pools.destroy');
        Route::patch('{assessment}/questions/reorder', [AssessmentQuestionController::class, 'reorder'])->name('assessments.questions.reorder');
        Route::put('{assessment}/questions/{question}', [AssessmentQuestionController::class, 'update'])->name('assessments.questions.update');
        Route::delete('{assessment}/questions/{question}', [AssessmentQuestionController::class, 'destroy'])->name('assessments.questions.destroy');
        Route::post('{assessment}/questions/{question}/duplicate', [AssessmentQuestionController::class, 'duplicate'])->name('assessments.questions.duplicate');
    });
    Route::prefix('management/question-bank')->middleware('assessment.manager')->group(function () {
        Route::get('/', [AssessmentQuestionBankController::class, 'index'])->name('assessments.question-bank');
        Route::post('/', [AssessmentQuestionBankController::class, 'store'])->name('assessments.question-bank.store');
        Route::post('import', [AssessmentQuestionBankController::class, 'import'])->name('assessments.question-bank.import');
        Route::put('{question}', [AssessmentQuestionBankController::class, 'update'])->name('assessments.question-bank.update');
        Route::post('{question}/duplicate', [AssessmentQuestionBankController::class, 'duplicate'])->name('assessments.question-bank.duplicate');
        Route::patch('{question}/archive', [AssessmentQuestionBankController::class, 'archive'])->name('assessments.question-bank.archive');
    });
    Route::middleware('assessment.manager')->get('management/assessment-media/{material}', [AssessmentMaterialController::class, 'show'])->name('assessments.media.show');
    Route::middleware('assessment.manager')->group(function () {
        Route::get('management/applicants', [JobApplicationController::class, 'index'])->name('applications.index');
        Route::put('management/applicants/{application}', [JobApplicationController::class, 'update'])->name('applications.update');
        Route::get('management/applicants/{application}/resume', [JobApplicationController::class, 'resume'])->name('applications.resume');
        Route::prefix('management/call-evaluations')->name('quality.evaluations.')->group(function () {
            Route::get('create', [CallEvaluationController::class, 'create'])->name('create');
            Route::post('/', [CallEvaluationController::class, 'store'])->name('store');
            Route::get('{evaluation}/edit', [CallEvaluationController::class, 'edit'])->name('edit');
            Route::put('{evaluation}', [CallEvaluationController::class, 'update'])->name('update');
            Route::post('{evaluation}/submit', [CallEvaluationController::class, 'submit'])->name('submit');
            Route::delete('{evaluation}', [CallEvaluationController::class, 'destroy'])->name('destroy');
        });
        Route::prefix('management/qa-scorecards')->name('quality.scorecards.')->group(function () {
            Route::get('/', [CallEvaluationScorecardController::class, 'index'])->name('index');
            Route::post('/', [CallEvaluationScorecardController::class, 'store'])->name('store');
            Route::get('{scorecard}/builder', [CallEvaluationScorecardController::class, 'builder'])->name('builder');
            Route::put('{scorecard}', [CallEvaluationScorecardController::class, 'update'])->name('update');
            Route::get('{scorecard}/preview', [CallEvaluationScorecardController::class, 'preview'])->name('preview');
            Route::post('{scorecard}/activate', [CallEvaluationScorecardController::class, 'activate'])->name('activate');
            Route::post('{scorecard}/archive', [CallEvaluationScorecardController::class, 'archive'])->name('archive');
            Route::post('{scorecard}/duplicate', [CallEvaluationScorecardController::class, 'duplicate'])->name('duplicate');
            Route::delete('{scorecard}', [CallEvaluationScorecardController::class, 'destroy'])->name('destroy');
            Route::post('{scorecard}/categories', [CallEvaluationScorecardChildController::class, 'storeCategory'])->name('categories.store');
            Route::put('{scorecard}/categories/{category}', [CallEvaluationScorecardChildController::class, 'updateCategory'])->name('categories.update');
            Route::delete('{scorecard}/categories/{category}', [CallEvaluationScorecardChildController::class, 'deleteCategory'])->name('categories.destroy');
            Route::patch('{scorecard}/categories/{category}/move', [CallEvaluationScorecardChildController::class, 'moveCategory'])->name('categories.move');
            Route::post('{scorecard}/categories/{category}/criteria', [CallEvaluationScorecardChildController::class, 'storeCriterion'])->name('criteria.store');
            Route::put('{scorecard}/categories/{category}/criteria/{criterion}', [CallEvaluationScorecardChildController::class, 'updateCriterion'])->name('criteria.update');
            Route::delete('{scorecard}/categories/{category}/criteria/{criterion}', [CallEvaluationScorecardChildController::class, 'deleteCriterion'])->name('criteria.destroy');
            Route::patch('{scorecard}/categories/{category}/criteria/{criterion}/move', [CallEvaluationScorecardChildController::class, 'moveCriterion'])->name('criteria.move');
        });
        Route::get('management/campaign-analytics', [CampaignAnalyticsController::class, 'index'])->name('campaign.analytics');
        Route::post('management/coaching', [CoachingManagementController::class, 'store'])->name('coaching.manage.store');
        Route::put('management/coaching/{coaching}', [CoachingManagementController::class, 'update'])->name('coaching.manage.update');
        Route::post('management/coaching/{coaching}/training', [CoachingManagementController::class, 'assignTraining'])->name('coaching.manage.training');
        Route::post('management/coaching/{coaching}/complete', [CoachingManagementController::class, 'complete'])->name('coaching.manage.complete');
        Route::get('management/assessment-assignments', [AssessmentAssignmentController::class, 'index'])->name('assessments.assignments');
        Route::get('management/assessment-assignment-schedule/preview', [\App\Http\Controllers\AssessmentAssignmentScheduleController::class, 'preview'])->name('assessments.assignments.schedule.preview');
        Route::patch('management/assessment-assignment-schedule', [\App\Http\Controllers\AssessmentAssignmentScheduleController::class, 'store'])->name('assessments.assignments.schedule.store');
        Route::post('management/assessment-assignments', [AssessmentAssignmentController::class, 'store'])->name('assessments.assignments.store');
        Route::put('management/assessment-assignments/{assignment}', [AssessmentAssignmentController::class, 'update'])->name('assessments.assignments.update');
        Route::delete('management/assessment-assignments/{assignment}', [AssessmentAssignmentController::class, 'destroy'])->name('assessments.assignments.destroy');
        Route::patch('management/assessment-assignments/deadlines/extend', [AssessmentAssignmentController::class, 'extendDeadlines'])->name('assessments.assignments.deadlines.extend');
        Route::get('management/assessment-employees', [AssessmentAssignmentController::class, 'employees'])->name('assessments.employees.search');
        Route::get('management/assessment-recipient-count', [AssessmentAssignmentController::class, 'countRecipients'])->name('assessments.assignments.count');
        Route::get('management/assessment-reviews', [AssessmentReportingController::class, 'pending'])->name('assessments.reports.pending');
        Route::get('management/assessment-reviews/{attempt}', [AssessmentReportingController::class, 'grade'])->name('assessments.reports.grade');
        Route::put('management/assessment-reviews/{attempt}', [AssessmentReportingController::class, 'saveGrade'])->name('assessments.reports.grade.save');
        Route::get('management/assessment-results', [AssessmentReportingController::class, 'results'])->name('assessments.reports.results');
        Route::get('management/assessment-results-export', [AssessmentReportingController::class, 'export'])->name('assessments.reports.export');
        Route::get('management/assessment-results/{assessment}/analytics', [AssessmentReportingController::class, 'assessment'])->name('assessments.reports.analytics');
        Route::get('management/assessment-teams/{team}/analytics', [AssessmentReportingController::class, 'team'])->name('assessments.reports.team');
    });
    Route::prefix('management/training-library')->middleware('assessment.manager')->group(function () {
        Route::get('/', [TrainingLibraryController::class, 'index'])->name('training-library.index');
        Route::post('/', [TrainingLibraryController::class, 'store'])->name('training-library.store');
        Route::put('{material}', [TrainingLibraryController::class, 'update'])->name('training-library.update');
        Route::post('{material}/duplicate', [TrainingLibraryController::class, 'duplicate'])->name('training-library.duplicate');
        Route::patch('{material}/archive', [TrainingLibraryController::class, 'archive'])->name('training-library.archive');
        Route::delete('{material}', [TrainingLibraryController::class, 'destroy'])->name('training-library.destroy');
        Route::get('{material}/preview', [TrainingLibraryController::class, 'preview'])->name('training-library.preview');
    });
    Route::middleware('assessment.manager')->group(function () {
        Route::post('management/assessments/{assessment}/training-library', [AssessmentTrainingAttachmentController::class, 'store'])->name('training-library.attach');
        Route::delete('management/assessments/{assessment}/training-library/{attachment}', [AssessmentTrainingAttachmentController::class, 'destroy'])->name('training-library.detach');
    });
});

require __DIR__.'/settings.php';
